[
  {
    "poster": {
      "poster_name": "Jamie Buck",
      "poster_handle": "jamie.william.buck"
    },
    "time_stamp": "2024-07-07 17:12:26",
    "text": "Hello - i am working with a HubSpot instance that has custom fields on the `Contact` which were originally created by an app in Supered.  When using the node SDK to update them - im getting the following vague error.\n\n```{\"status\":\"error\",\"message\":\"There was an error processing the request.\",\"correlationId\":\"78e90499-98a5-4f7d-8a1b-bb13117f5cc5\",\"category\":\"INTERNAL_ERROR\"}```\nMy sdk implementation looks like this:\n```const userUpdate = await HubSpotClient.crm.contacts.basicApi.update(\n  \"REDACTED\",\n  {\n    properties: {\n      pt_everywhere_id_patched: \"NEW_VALUE\",\n    },\n  }\n);```\nThe fields _are_ marked as sensitive/hipaa, but i have the following scopes on my private app:\n```crm.objects.contacts.sensitive.read\ncrm.objects.contacts.sensitive.write\ncrm.schemas.deals.write\ncrm.schemas.contacts.write\ncrm.objects.contacts.write\ncrm.schemas.deals.read\ncrm.objects.contacts.read\ncrm.schemas.contacts.read```",
    "reply_count": 2,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2024-07-07 18:25:46"
      },
      {
        "time_stamp": "2024-07-07 18:26:06"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Jamie Buck",
      "poster_handle": "jamie.william.buck"
    },
    "time_stamp": "2024-07-07 18:25:46",
    "text": "Im also confiden i have the correct scopes set because if i remove the `.sensitive.` ones - i get an error message specific to incorrect/missing scopes"
  },
  {
    "poster": {
      "poster_name": "Jamie Buck",
      "poster_handle": "jamie.william.buck"
    },
    "time_stamp": "2024-07-07 18:26:06",
    "text": "Im able to do things like this no problem\n\n```const userUpdate = await HubSpotClient.crm.contacts.basicApi.update(\n  \"REDACTED\",\n  {\n    properties: {\n      email: \"<mailto:foo@bar.com|foo@bar.com>\",\n    },\n  }\n);```"
  }
]