[
  {
    "poster": {
      "poster_name": "Phatthanaphong Thongthip",
      "poster_handle": "pthongth"
    },
    "time_stamp": "2022-05-23 01:15:35",
    "text": "Hi"
  },
  {
    "poster": {
      "poster_name": "Phatthanaphong Thongthip",
      "poster_handle": "pthongth"
    },
    "time_stamp": "2022-05-23 01:15:59",
    "text": "I try to implement by following this guide <https://github.com/HubSpot/sample-apps-oauth/blob/main/node/src/index.js>"
  },
  {
    "text": "I still can't authorize by url",
    "time_stamp": "2022-05-23 01:16:39"
  },
  {
    "poster": {
      "poster_name": "Corentin Guillo",
      "poster_handle": "corentin.guillo-ext"
    },
    "time_stamp": "2022-05-23 03:20:21",
    "text": "Hi, thanks for the message <@U03828U9C2E> but I have tried with the API key as well (which I shouldn't need to have since I'm not an admin, token should be enough). It doesn't work either"
  },
  {
    "poster": {
      "poster_name": "Ed Jones",
      "poster_handle": "ed.jones"
    },
    "time_stamp": "2022-05-23 04:14:56",
    "text": "Hi All,\nNew to APIs, so apologies if this has already been covered. I want to start using HubSpot tracking and their cookie consent mechanism. But it doesn't support the management of third party cookies.\nI've been told the Event API can be used to pass on consent outcome to trigger the Google Tag Manager script - which is what I use to deploy my third party cookies. Has anyone successfully done this and can guide me through? So far my attempts to configure this have been largely unsuccessful.\nI'm relying on these resources, but have yet to solve this issue:\n• <https://developers.HubSpot.com/docs/api/events/cookie-banner>\n• <https://community.HubSpot.com/t5/GDPR/HubSpot-Google-Tag-Manager-and-cookie-consent/m-p/488151>\n• <https://community.HubSpot.com/t5/APIs-Integrations/cookie-tracking-in-banner-with-GA/m-p/271193>\n"
  },
  {
    "poster": {
      "poster_name": "Nicole Pereira",
      "poster_handle": "nicole847"
    },
    "time_stamp": "2022-05-23 14:37:48",
    "text": "can a VID be updated or appended when trying to backfill VIDs for contacts that came over via API without them?"
  },
  {
    "poster": {
      "poster_name": "Ihor Khrypchenko",
      "poster_handle": "khrypchenko.ihor"
    },
    "time_stamp": "2022-05-23 15:37:53",
    "text": "Hello everyone. I have question about case\n\n`Client error: POST &lt;<https://api.hubapi.com/filemanager/api/v3/files/upload>&gt; resulted in a 403 Forbidden response:\\n{\"status\":\"error\",\"message\":\"HIGH_RISK_PORTAL\",\"correlationId\":\"dadb8ebf-838a-4bf9-8ace-7b9c3ffa346f\"}`\n\nPlease contact me."
  },
  {
    "poster": {
      "poster_name": "Cosmin Almajanu",
      "poster_handle": "almajanu.cosmin"
    },
    "time_stamp": "2022-05-23 16:08:06",
    "edited": {
      "time_stamp": "2022-05-23 16:10:21"
    },
    "text": "Hi everyone,\n\nI am trying to use change subscriberState for an external event. I am receiving a weird response back from the API.\n\n```{'category': None,\n'context': None,\n'correlation_id': None,\n'errors': None,\n'links': None,\n'message': None,\n'sub_category': None}```\n\nWhen I then get the data for the external event I do not see the registered participant.\n\nI am using the python library and my code looks like this\n```from HubSpot import HubSpot\nfrom HubSpot.marketing.events.exceptions import ApiException\nfrom HubSpot.marketing.events.models.batch_input_marketing_event_email_subscriber import BatchInputMarketingEventEmailSubscriber\n\nimport time\n\napi_client = HubSpot()\napi_client.access_token = 'xxxxx'\n\n\n#format time to unix time for HubSpot API\nreg_datetime = int(time.time_ns() / 1000 )\nprint(reg_datetime)\n\nexternalAccountID = xxxx\nexternalEventID = xxx\n\nsubscriber_state = \"register\" \n\n#set the email and interaction date for subscribers\ninputs = [{\"interactionDateTime\":reg_datetime,\"email\":\"<mailto:cosmin@testing.com|cosmin@testing.com>\"}]\ncontact_inputs = BatchInputMarketingEventEmailSubscriber(inputs)\n\n\ntry:\n   mktevent_substate = api_client.marketing.events.subscriber_state_changes_api.do_email_upsert_by_id(externalEventID,subscriber_state, externalAccountID, contact_inputs )\nexcept ApiException as e:\n   print(\"Exception raised: %s\\n\" % e)\nprint(mktevent_substate)\n\n#Verify change\nget_external_event = api_client.marketing.events.basic_api.get_by_id(externalEventID, externalAccountID)\nprint(get_external_event)```\n\nCan anyone figure out if I’m doing something wrong?"
  },
  {
    "text": "Hi there. We're having a strange issue with pushing contact data via the API. We have a form with a mixture of field types, and two checkbox field sets. One the checkbox fields has no problem with this data being submitted and being correctly applied against the contact, but the other doesn't work as expected. Instead of checking on individual checkboxes, the contact ends up with single concatenated field with all of the selected values – see below :point_down:",
    "time_stamp": "2022-05-23 23:30:29"
  },
  {
    "text": "The data being submitted correctly matches the expected format for API:",
    "time_stamp": "2022-05-23 23:31:20"
  },
  {
    "poster": {
      "poster_name": "Riziq Maulana",
      "poster_handle": "riziq.maulana"
    },
    "time_stamp": "2022-05-23 23:39:03",
    "text": "Hallo Corentin, is your api correct? make sure it's correct. I think it should be work"
  }
]