[
  {
    "text": "Hello Team, I'm using Contacts Archive batch API in postman and try to archive the contacts based on their ids. So in case of correct ids, it returns 204 code but when I tried with the wrong value of ids it returns me the same 204 code. I think it should return an error like `id not found or not exist`.\nCan anyone confirm this? It is the expected behavior from HubSpot or it is a bug?",
    "time_stamp": "2020-08-07 07:17:32",
    "reply_count": 4,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2020-08-07 12:34:53"
      },
      {
        "time_stamp": "2020-08-11 06:26:16"
      },
      {
        "time_stamp": "2020-08-12 11:45:28"
      },
      {
        "time_stamp": "2020-08-13 06:04:23"
      }
    ]
  },
  {
    "subtype": "tombstone",
    "text": "This message was deleted.",
    "time_stamp": "2020-08-07 11:11:57",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2020-08-07 11:14:03"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Shani",
      "poster_handle": "hsdeveloper6"
    },
    "time_stamp": "2020-08-07 11:14:03",
    "text": "Please remove the API key. That should not be for public."
  },
  {
    "poster": {
      "poster_name": "Chandler Ives",
      "poster_handle": "cives727"
    },
    "time_stamp": "2020-08-07 11:25:50",
    "text": "Hi all, any idea why I am getting a 404 error when trying to update an existing record using HS API (<https://legacydocs.HubSpot.com/docs/methods/contacts/update_contact>) The actual call looks like (<https://api.hubapi.com/contacts/v1/contact/vid/5393601/profile/?hapikey=my-api-key>)\n\nDoes anything look structurally wrong? I get this error when trying to update any record.",
    "reply_count": 2,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2020-08-07 12:16:20"
      },
      {
        "time_stamp": "2020-08-07 12:31:22"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Shani",
      "poster_handle": "hsdeveloper6"
    },
    "time_stamp": "2020-08-07 12:16:20",
    "text": "Could you please send the screenshot of the error you are receiving ?"
  },
  {
    "poster": {
      "poster_name": "Matthew Hall",
      "poster_handle": "mhall"
    },
    "time_stamp": "2020-08-07 12:28:54",
    "text": "I have had similar issues w/ some other V3 APIs missing features. UPSERTing contacts to prevent race conditions does not work (yet) in V3"
  },
  {
    "poster": {
      "poster_name": "Matthew Hall",
      "poster_handle": "mhall"
    },
    "time_stamp": "2020-08-07 12:31:22",
    "edited": {
      "time_stamp": "2020-08-07 12:31:51"
    },
    "text": "you appear to be off by one slash char:\n\n`<https://api.hubapi.com/contacts/v1/contact/vid/5393601/profile?hapikey=hapikey>`"
  },
  {
    "poster": {
      "poster_name": "Matthew Hall",
      "poster_handle": "mhall"
    },
    "time_stamp": "2020-08-07 12:33:47",
    "text": "Of course, I use it daily in my integration\n\n<https://legacydocs.HubSpot.com/docs/methods/engagements/engagements-overview>\n\nYou can put a body on them to have comments / data made visible in the UI... it uses a weird dialect of HTML which you can learn how to generate by making ones that look right in the UI and then seeing the HTML payload it generated when you pull back the data"
  },
  {
    "poster": {
      "poster_name": "Matthew Hall",
      "poster_handle": "mhall"
    },
    "time_stamp": "2020-08-07 12:34:53",
    "text": "Is the behavior the same in non-batch mode? Some batch APIs skip over minor errors for flexibility / performance reasons"
  }
]