[
  {
    "poster": {
      "poster_name": "Fabian Glaw",
      "poster_handle": "fabian643"
    },
    "time_stamp": "2022-07-06 04:39:52",
    "text": "Hello everyone,\nI have an issue with form submissions. I was running some jquery to change the apperance of the form, so that I can have some sections.\nIt works great if the form is filled out completely and then submitted.\nIf the submit button is clicked before all required fields are filled out, then all missing fields are being filled out and then the submit button is clicked again it throws the following error:\n```Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.\n    at i (v2.js:1:116521)\n    at Object.processUpdates (v2.js:1:11205)\n    at Object.dangerouslyProcessChildrenUpdates [as processChildrenUpdates] (v2.js:1:54625)\n    at s (v2.js:1:80095)\n    at o.updateChildren (v2.js:1:80787)\n    at o._updateDOMChildren (v2.js:1:52766)\n    at o.updateComponent (v2.js:1:51290)\n    at o.receiveComponent (v2.js:1:51158)\n    at Object.receiveComponent (v2.js:1:88531)\n    at u._updateRenderedComponent (v2.js:1:44761)```\nThe Error is the following:\n```ErrorEvent\nisTrusted: true\nbubbles: false\ncancelBubble: false\ncancelable: true\ncolno: 116771\ncomposed: false\ncurrentTarget: Window {0: Window, 1: Window, 2: global, 3: Window, 4: Window, window: Window, self: Window, document: document, name: '', location: Location, …}\ndefaultPrevented: false\nerror: Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings. at i (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:116521>) at Object.processUpdates (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:11205>) at Object.dangerouslyProcessChildrenUpdates [as processChildrenUpdates] (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:54625>) at s (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:80095>) at o.updateChildren (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:80787>) at o._updateDOMChildren (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:52766>) at o.updateComponent (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:51290>) at o.receiveComponent (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:51158>) at Object.receiveComponent (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:88531>) at u._updateRenderedComponent (<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js:1:44761>)\neventPhase: 0\nfilename: \"<https://25256994.hs-sites-eu1.com/_hcms/forms/v2.js>\"\nlineno: 1\nmessage: \"Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.\"\npath: [Window]\nreturnValue: true\nsrcElement: Window {0: Window, 1: Window, 2: global, 3: Window, 4: Window, window: Window, self: Window, document: document, name: '', location: Location, …}\ntarget: Window {0: Window, 1: Window, 2: global, 3: Window, 4: Window, window: Window, self: Window, document: document, name: '', location: Location, …}\ntimeStamp: 32077.599999999627\ntype: \"error\"\n[[Prototype]]: ErrorEvent```\nsomehow my custom code has a conflict with HubSpots forms/v2.js :thinking_face:\nDo you have any recommendations how to debug this o what could be the issue?\nThank you for your help",
    "reply_count": 4,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2022-07-06 06:43:52"
      },
      {
        "time_stamp": "2022-07-06 06:45:39"
      },
      {
        "time_stamp": "2022-07-06 07:06:36"
      },
      {
        "time_stamp": "2022-07-06 09:27:43"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Derek Cavaliero",
      "poster_handle": "derek168"
    },
    "time_stamp": "2022-07-06 06:43:52",
    "text": "ive seen this happen before, the only thing I can think of is that because HubSpot uses react to render the forms and handle the validation/submission functionality, that any excessive changes to the DOM structure of the form itself could cause an exception for various reasons. Appending elements to existing elements in the form seems to work fine, but once you start wrapping elements inside other elements things can start getting whacky."
  },
  {
    "poster": {
      "poster_name": "Derek Cavaliero",
      "poster_handle": "derek168"
    },
    "time_stamp": "2022-07-06 06:45:39",
    "text": "the reason it throws the exception only with validation errors is likely due to it attempting to update the UI with the error messages and something internally is erroring out (hard to say what - their exception catching/throwing is rather unhelpful)."
  },
  {
    "poster": {
      "poster_name": "Fabian Glaw",
      "poster_handle": "fabian643"
    },
    "time_stamp": "2022-07-06 07:06:36",
    "edited": {
      "time_stamp": "2022-07-06 07:06:57"
    },
    "text": "Thank you for your thoughts Derek, I keep on investigating"
  },
  {
    "poster": {
      "poster_name": "Fabian Glaw",
      "poster_handle": "fabian643"
    },
    "time_stamp": "2022-07-06 09:27:43",
    "text": "The error is thrown after the last required field is filled out. before the submit button is clicked again"
  }
]