[
  {
    "poster": {
      "poster_name": "Babu Balakrishnan",
      "poster_handle": "babu"
    },
    "time_stamp": "2024-01-23 02:35:58",
    "text": "Thanks for the help Matt. It solves my problem\n\nSince I am capturing referred people (email) as contact, and I need to get list of people referred by the user(referrer),\n\nI am able to get it using single Contacts search API call\n\ncontact_search_endpoint = '<https://api.hubapi.com/crm/v3/objects/contacts/search>'\n\nfilters = [{'propertyName':'xxxx_referred_by_xxxxxx', 'value':'<mailto:referrer_email@domain.com|referrer_email@domain.com>', 'operator':'EQ'}]\nproperties = []\n\ndata = {'filterGroups': [{ 'filters': filters }], 'properties': properties, 'limit': 100, 'after': 0}\n\n// python request\n<http://requests.post|requests.post>(url=contact_search_endpoint, data=json.dumps(data), headers=HEADERS)"
  },
  {
    "poster": {
      "poster_name": "Matt Scott",
      "poster_handle": "mscott"
    },
    "time_stamp": "2024-01-23 02:51:59",
    "edited": {
      "time_stamp": "2024-01-23 02:53:29"
    },
    "text": "Awesome! glad I could help!\nIn the original post you mentioned just having the contact ID which is where the first step would have come in to get the email, but since you already have the email you don’t need to do that"
  },
  {
    "poster": {
      "poster_name": "Clayton Sardella",
      "poster_handle": "clayton.sardella"
    },
    "time_stamp": "2024-01-23 08:27:04",
    "text": "Hello All, I am currently working on pulling all users' Internal Values from our portal to assist with analytics that utilize these values. I am attempting to retrieve the data from the Contact Owner using the API Endpoint '<https://api.hubapi.com/properties/v1/contacts/properties/named/HubSpot_owner_id>.' However, when I perform the GET request, the result is blank.\n\nIf anyone has experience exporting the User's Internal Value from an API or can offer guidance on resolving this issue, your assistance would be greatly appreciated.",
    "reply_count": 1,
    "reply_users_count": 1,
    "replies": [
      {
        "time_stamp": "2024-01-24 07:50:24"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas689"
    },
    "time_stamp": "2024-01-23 09:59:08",
    "text": "i think i broke the search api for notes; i sent in a couple thousand batches for notes to be deleted and now when I search for any note in HS for a criteria that was returing a bunch I get:\n\n```{\n    \"total\": 15,\n    \"results\": []\n}```\neven if I change the query"
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas689"
    },
    "time_stamp": "2024-01-23 09:59:23",
    "text": "has anyone experienced this? I'm guessing the transactional database is locking me out?"
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas689"
    },
    "time_stamp": "2024-01-23 10:00:53",
    "text": "hmmm I think the delete call was just taking a while to process - took about a half hour. now I get the correct \"0\" results",
    "reply_count": 3,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2024-01-23 10:47:55"
      },
      {
        "time_stamp": "2024-01-23 10:48:09"
      },
      {
        "time_stamp": "2024-01-23 10:48:47"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 10:47:55",
    "text": "search api can tend to lag behind real time results. could have just been that — only way to verify would have been to try to access note by id directly "
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 10:48:09",
    "text": "could have been the massive batch as well"
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas689"
    },
    "time_stamp": "2024-01-23 10:48:47",
    "text": "yeah makes sense and im glad its transactions"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 10:55:11",
    "text": "Hi all! Curious if anyone has run into this issue or has any insights: I am running a basic company delete, sending a DELETE request to `<https://api.hubapi.com/crm/v3/objects/companies/{objectId}>` . I get a 204 back as expected. However when I check in the UI that company still exists. I have tried the same request in a different portal and it works as expected (the company is no longer available in the UI). The portal in question has the SFDC integration on, but as I understand it that should only affect merges, not deletes. Any ideas? Thanks in advance!",
    "reply_count": 21,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2024-01-23 10:59:09"
      },
      {
        "time_stamp": "2024-01-23 10:59:17"
      },
      {
        "time_stamp": "2024-01-23 11:04:07"
      },
      {
        "time_stamp": "2024-01-23 11:26:37"
      },
      {
        "time_stamp": "2024-01-23 11:35:49"
      },
      {
        "time_stamp": "2024-01-23 11:37:01"
      },
      {
        "time_stamp": "2024-01-23 11:37:17"
      },
      {
        "time_stamp": "2024-01-23 11:37:24"
      },
      {
        "time_stamp": "2024-01-23 11:37:45"
      },
      {
        "time_stamp": "2024-01-23 11:39:15"
      },
      {
        "time_stamp": "2024-01-23 11:39:37"
      },
      {
        "time_stamp": "2024-01-23 11:40:00"
      },
      {
        "time_stamp": "2024-01-23 11:41:10"
      },
      {
        "time_stamp": "2024-01-23 11:41:23"
      },
      {
        "time_stamp": "2024-01-23 11:41:58"
      },
      {
        "time_stamp": "2024-01-23 11:43:28"
      },
      {
        "time_stamp": "2024-01-23 11:51:17"
      },
      {
        "time_stamp": "2024-01-23 11:52:39"
      },
      {
        "time_stamp": "2024-01-23 11:54:08"
      },
      {
        "time_stamp": "2024-01-23 11:56:03"
      },
      {
        "time_stamp": "2024-01-23 11:57:23"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 10:59:09",
    "text": "You might want to go to the company record and make sure all your timeline filters are on. Then you can determine if it is being deleted, if it is being created, etc."
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 10:59:17",
    "text": "does it have a “create date” of just after you deleted it?"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 11:04:07",
    "text": "Oh good call, but no it doesn’t, has the original create date and all the old timeline data. Furthermore I can successfully delete the record using the UI, but unfortunately I need the API cuz I’ve got hundreds/thousands to do"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:26:37",
    "text": "have you attempted to delete an invalid company id? Does that give a 204?\n\nHave you attempted batch archiving with just one record? See how that works?\n\nsuper odd"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 11:35:49",
    "text": "Deleting an invalid company returns a 204, which is the same behavior that I see in the portal where deleting works.\nBatch endpoint has the same behavior, returns a 204 but no delete.\nTotally odd… I feel like it has to be something simple/stupid but can’t figure it out"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:37:01",
    "text": "want to share your code?"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:37:17",
    "text": "are you doing this in postman? somewhere else?"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 11:37:24",
    "text": "I suppose a workaround could be tagging some property with the api and then using the filter in UI to mass delete"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 11:37:45",
    "text": "its a node script,  but now I’m using postman to test with same results"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:39:15",
    "text": "private app has proper scopess?"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:39:37",
    "text": "can you update a company property? Change some property on the compnay?"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 11:40:00",
    "text": "oh good call, ill try that"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:41:10",
    "text": "What is odd is the 204 for deleting valid and invalid record"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:41:23",
    "text": "is it possible you are using wrong private app key?"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 11:41:58",
    "text": "I will quadruple check, but I’m pretty sure its right"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:43:28",
    "text": "thats what I was hoping to see by you updating that company property — if it didn’t update it, is might be the wrong app key"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 11:51:17",
    "text": "damn, i feel stupid… it was definitely the wrong private app key :disappointed:"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 11:52:39",
    "text": "whats weird is that all the other calls in my script failed silently…. like i was retrieving associated contacts from a company… and those requests came back as no results rather than an error"
  },
  {
    "poster": {
      "poster_name": "Schuyler Maclay",
      "poster_handle": "smaclay"
    },
    "time_stamp": "2024-01-23 11:54:08",
    "text": "annnyway, thanks so much for all the help, sorry it ended up being so silly"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:56:03",
    "text": "I’ve done much worse lol"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 11:57:23",
    "text": "no problem — listen, that is why there is a whole debugging process, check what you think first, then go down the rabbit hole of all the mistakes you’ve made before lol"
  },
  {
    "poster": {
      "poster_name": "Mariana Forteza",
      "poster_handle": "mariana"
    },
    "time_stamp": "2024-01-23 11:58:35",
    "text": "Hello, did you find a solution for this?"
  },
  {
    "poster": {
      "poster_name": "Mariana Forteza",
      "poster_handle": "mariana"
    },
    "time_stamp": "2024-01-23 12:01:05",
    "text": "Hello, was this issue ever solved? I having the same problem and seems like the search api is still working th same way"
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas689"
    },
    "time_stamp": "2024-01-23 12:20:05",
    "text": "anyone know off hand what HubSpot expects for a type to be sent in as for the deals API whe nsetting product discount?"
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas689"
    },
    "time_stamp": "2024-01-23 12:20:14",
    "text": "seems like straight numerical doesnt work",
    "reply_count": 2,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2024-01-23 15:03:27"
      },
      {
        "time_stamp": "2024-01-23 15:37:39"
      }
    ]
  },
  {
    "subtype": "thread_broadcast",
    "time_stamp": "2024-01-23 14:29:07",
    "text": "After a lot of back and forth with HubSpot support, it was determined that the API docs were a bit off on these endpoints.  By updating my `customProperties` to use the `name/value` model seen below, everything worked as expected.\n\n```{\n    \"startDateTime\": \"2024-11-30T17:46:20.461Z\",\n    \"externalEventId\": \"2\",\n    \"eventOrganizer\": \"Event Organizer\",\n    \"eventName\": \"Test Event\",\n    \"externalAccountId\": \"7777\",\n    \"customProperties\": [\n       {\"name\": \"ftc_sei\", \"value\": \"1234\"}\n     ]\n}```\nNot sure if they are going to update those docs or not as they didn't seem like it was high priority and told me they'd take it under advisement when I recommended the update, but if anyone comes across this issue, I hope this helps!"
  },
  {
    "poster": {
      "poster_name": "Nicholas Decker - Level -22",
      "poster_handle": "nickdeckerdevs"
    },
    "time_stamp": "2024-01-23 15:03:27",
    "text": "discounts! why are you setting discounts!"
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas558"
    },
    "time_stamp": "2024-01-23 15:37:39",
    "text": "lol"
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas558"
    },
    "time_stamp": "2024-01-23 15:38:30",
    "text": "what I did was search for one by ID that I know works and then look at how its formatted in the body and copy that"
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas558"
    },
    "time_stamp": "2024-01-23 15:38:46",
    "text": "cuz HubSpot will throw in random &lt;br/&gt; tags and such"
  },
  {
    "poster": {
      "poster_name": "Thomas Lane",
      "poster_handle": "thomas558"
    },
    "time_stamp": "2024-01-23 15:39:06",
    "text": "and use wildcards"
  },
  {
    "poster": {
      "poster_name": "Duryab Aziz Sukhera",
      "poster_handle": "sukhera777"
    },
    "time_stamp": "2024-01-23 15:39:11",
    "text": ""
  },
  {
    "poster": {
      "poster_name": "Dennis Jiang",
      "poster_handle": "dennis.jiang"
    },
    "time_stamp": "2024-01-23 20:26:38",
    "text": ":wave: Hello, team!\nCan anyone help on the API permission issue as posted in\n<https://community.HubSpot.com/t5/APIs-Integrations/App-tickets-scope-and-corresponding-user-permissions/m-p/909974#M70498>\n\nPer this document <https://developers.HubSpot.com/docs/api/working-with-oauth>\nusers can install app if they have <https://knowledge.HubSpot.com/settings/HubSpot-user-permissions-guide?_ga=2.38183523.1708489874.1705900364-679154558.1704933791&amp;_gl=1*1tda7aa*_ga*Njc5MTU0NTU4LjE3MDQ5MzM3OTE.*_ga_LXTM6CQ0XK*MTcwNjAwMTYyNi4xOC4xLjE3MDYwMDQ3MzAuNTQuMC4w#settings|App Marketplace Access> permissions.\nIn our app, we required \"tickets\" scope and granted a user tickets and App Marketplace Access permissions, but he still can't install the app, the error says \"Couldn’t complete the connection You don’t have permission to connect this app.\" Not sure what happened, what permissions shound be granted to the user if the app requires \"tickets\" scope, any help is appreciated.",
    "reply_count": 2,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2024-01-24 05:28:57"
      },
      {
        "time_stamp": "2024-01-25 03:36:31"
      }
    ]
  },
  {
    "subtype": "tombstone",
    "text": "This message was deleted.",
    "time_stamp": "2024-01-23 21:21:32",
    "reply_count": 4,
    "reply_users_count": 3,
    "replies": [
      {
        "time_stamp": "2024-01-24 02:20:42"
      },
      {
        "time_stamp": "2024-01-24 02:21:09"
      },
      {
        "time_stamp": "2024-01-24 02:21:54"
      },
      {
        "time_stamp": "2024-01-24 10:48:36"
      }
    ]
  }
]