[
  {
    "text": "Hi everyone, created a custom module with a video included and additional .vtt files.\n```&lt;video&gt;\n  &lt;source src=\"{{module.video_full_url.href}}\" type=\"video/mp4\" crossorigin=\"anonymous\"&gt;\n  {% if content.language.languageTag == \"de\" %}\n  &lt;track label=\"Deutsch\" kind=\"captions\" srclang=\"de\" src=\"{{module.video_track_caption.href}}\" default&gt;\n  {% elif content.language.languageTag == \"en\" %}\n  &lt;track label=\"English\" kind=\"captions\" srclang=\"en\" src=\"{{module.video_track_caption.href}}\" default&gt;\n  {% endif %}\n&lt;/video&gt;```\nUploaded .vtt files into the HS-Filemanager, but I get an error:",
    "time_stamp": "2024-02-13 06:30:56"
  }
]