[
  {
    "poster": {
      "poster_name": "Matthew James",
      "poster_handle": "matthew929"
    },
    "time_stamp": "2023-02-18 07:19:35",
    "text": "im getting this error when running the deploy command\n```[ERROR] The build failed due to an internal error with id `c71a1693-49bb-4e3c-bb80-8a76537d0355`. Try uploading it again. If the problem persists, contact HubSpot support with the error id.```",
    "reply_count": 3,
    "reply_users_count": 2,
    "replies": [
      {
        "time_stamp": "2023-02-18 22:07:21"
      },
      {
        "time_stamp": "2023-02-21 09:38:01"
      },
      {
        "time_stamp": "2023-02-21 09:56:06"
      }
    ]
  },
  {
    "poster": {
      "poster_name": "Timothy Finley",
      "poster_handle": "tfinley"
    },
    "time_stamp": "2023-02-18 22:07:21",
    "text": "Sorry about that, took me longer than I thought to get to you. It looks like we have an internal problem with running out of disk space where the build is occurring. We might not be able to resolve that until early next week. But Iâ€™ll see what we can do. :crossed_fingers:"
  }
]