[
  {
    "text": "<@U2H3TT8F2> I already opened a support ticket but figured you guys might know more about the change.\n\nBasically this is what's happening now:",
    "time_stamp": "2024-04-28 19:47:44"
  },
  {
    "poster": {
      "poster_name": "Daniel Wong",
      "poster_handle": "dan.wong"
    },
    "time_stamp": "2024-04-28 19:48:13",
    "text": "so the other values were from before the change, which now causes IDs to be outputted instead of a url"
  },
  {
    "text": "I tried to do a temp workaround (not sustainable regardless as you can only call file_by_id 10 times per page) but even then the file URL returned isn't valid and it goes to a 404",
    "time_stamp": "2024-04-28 19:49:20"
  },
  {
    "poster": {
      "poster_name": "Daniel Wong",
      "poster_handle": "dan.wong"
    },
    "time_stamp": "2024-04-28 19:50:26",
    "edited": {
      "time_stamp": "2024-04-28 19:50:32"
    },
    "text": "I have a dynamic page which references a custom object as a datasource and this whole change breaks the module using it"
  },
  {
    "poster": {
      "poster_name": "Daniel Wong",
      "poster_handle": "dan.wong"
    },
    "time_stamp": "2024-04-28 19:54:14",
    "text": "here's a sample output of file_by_id which returns a 404:\n<https://dmcc.ae/hubfs/crm-properties-file-values/MFTL%20France%20-%20Event%20page%20banner%20(2).png>"
  }
]